version: '3.4'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash -c "npx ng serve --host 0.0.0.0"
    volumes:
      - ./:/opt/frontend:Z
    tty: true
    ports:
      - "4200:4200"
